// frontend-svelte/src/routes/cycle/[cycle]/week/[week]/+page.svelte
<script lang="ts">
  import Workout from '$lib/components/Workout.svelte';
  import { days } from '$lib/constants';
  import type { BaseWeights } from '$lib/types';

  export let data: { cycle: number; day: number; baseWeights: BaseWeights };
</script>

{#each days as day}
  <div class="mx-2">
    <Workout baseWeights={data.baseWeights} cycle={data.cycle} week={data.week} {day} />
  </div>
{/each}

// frontend/src/app/cycle/[cycle]/week/[week]/page.tsx
import Workout from '@components/workout';
import { days } from '@utils/constants';
import { safeParseInt } from '@utils/helpers';

interface WeekPageProps {
    params: {
        week: string;
        cycle: string;
    };
}

const WeekPage = ({ params }: WeekPageProps) => {
    const cycle = safeParseInt(params.cycle);
    const week = safeParseInt(params.week);
    if ((week !== 1 && week !== 2 && week !== 3) || !cycle) throw new Error('breh');

    return days.map((day) => (
        <div className="mx-2" key={`workout-${day}-${week}-${cycle}`}>
            <Workout cycle={cycle} week={week} day={day} />
        </div>
    ));
};

export default WeekPage;
