// frontend-svelte/src/lib/components/DateBoxForm.svelte
<script lang="ts">
  import { format, formatISO, parseISO } from 'date-fns';
  import type { Week, Day } from '$lib/types';
  import { onMount } from 'svelte';

  export let cycle: number;
  export let week: Week;
  export let day: Day;
  export let date: Date | undefined;
  export const profile: number = 1;

  const putDate = async () => {
    const response = await fetch(
      `/api/workout/date?profile=${profile}&cycle=${cycle}&week=${week}&day=${day}`,
      {
        method: 'PUT',
        body: JSON.stringify({ date: formatISO(date) }),
        headers: {
          'Content-Type': 'application/json'
        }
      }
    );

    if (response.status === 200) {
      const data = await response.json();
      date = parseISO(data.date);
    }
  };

  onMount(async () => {
    const response = await fetch(
      `/api/workout/date?profile=${profile}&cycle=${cycle}&week=${week}&day=${day}`
    );

    if (response.status === 200) {
      const data = await response.json();
      date = parseISO(data.date);
    }
  });
</script>

{#if date === undefined}
  <input name="date" class="border-2 rounded-md border-sky-500" type="date" bind:value={date} />
  <button on:click={putDate}>Go</button>
{:else}
  <div class="grid grid-flow-col items-center text-start">
    <button class="text-sm">{format(parseISO(date), 'EEEE dd. MMMM yyyy')}</button>
  </div>
{/if}

// frontend/src/components/client/date-box-form.tsx
'use client';

import { type ChangeEvent, useId, useState, useEffect } from 'react';
import { format, parse } from 'date-fns';
import { nb } from 'date-fns/locale';
import { getDate, setDate } from '@/actions/date';
import type { Week, Day } from '@/schema/workout';
import Spinner from '@/components/client/spinner';

interface Props {
    cycle: number;
    week: Week;
    day: Day;
}

const DateBoxForm = ({ cycle, week, day }: Props) => {
    const id = useId();

    const [exsistingDate, setExsistingDate] = useState<Date | undefined>();
    const [loading, setLoading] = useState<boolean>(false);

    useEffect(() => {
        const fetchReps = async () => {
            setLoading(true);
            const date = await getDate({ cycle, week, day });
            setLoading(false);

            if (!date) return;

            // :)
            setExsistingDate(date.date);
        };
        void fetchReps();
    }, [cycle, day, week]);

    const handleOnChange = async (event: ChangeEvent<HTMLInputElement>) => {
        const parsedDate = parse(event.currentTarget.value, 'yyyy-MM-dd', new Date());

        setLoading(true);
        await setDate({ cycle, week, day, date: parsedDate });
        setExsistingDate(parsedDate);

        setLoading(false);
    };

    return (
        <>
            {!exsistingDate && (
                <>
                    <input
                        id={id}
                        className="border-2 rounded-md border-sky-500"
                        type="date"
                        name="dateStr"
                        onChange={handleOnChange}
                    />
                    <label htmlFor={id} hidden>
                        Workout date
                    </label>
                </>
            )}
            {exsistingDate && (
                <>
                    <div className="grid grid-flow-col items-center text-start">
                        <p className="text-sm">{format(exsistingDate, 'EEEE dd. MMMM yyyy', { locale: nb })}</p>
                    </div>
                    {loading && <Spinner />}
                </>
            )}
        </>
    );
};

export default DateBoxForm;
